print ("########################################")
print ("#        ALOGORITMO EM PYTHON          #")
print ("########################################")
print ("# Escolha a opçao desejada:            #")
print ("#                                      #")
print ("# 1. Fibonacci                         #")
print ("########################################")